### ISSUE TITLE
react-native-sensitive-info Android Keystore Fake News

### ISSUE THREAD

**Issue by jfilter** [CodingZeal/redux-persist-sensitive-storage#14]
Hey,

I just want to clarify that `react-native-sensitive-info` actually uses the Android keystore. Check also: https://github.com/mCodex/react-native-sensitive-info/issues/59

✌️

**Comment by randycoulman** [comment]
Thanks for providing this update.  Nice to see that there's been some forward movement on this.

I did a little bit of digging and found this:

According to their release notes (see https://github.com/mCodex/react-native-sensitive-info/releases/tag/5.0.1), the keystore support was in master for 5.0.0, but pulled back out in 5.0.1.

Their [README](https://github.com/mCodex/react-native-sensitive-info#introduction) also continues to state that it uses Android Shared Preferences.

From what I can see in looking at the commit history, it looks like the keystore support was added back in [a commit with the subject "updates"](https://github.com/mCodex/react-native-sensitive-info/commit/bc76e3e3f2215377556eb137a3f89662498584b1) and is part of 5.2.0 which is still in pre-release status.  But the addition of the keystore support is not documented in the release notes for 5.2.0.

When 5.2.0 is officially released (and their documentation and release notes are updated), we'll update our docs here to reflect the change.
