### ISSUE TITLE
Losing Data on IOs

### ISSUE THREAD

**Issue by obsidianart** [CodingZeal/redux-persist-sensitive-storage#18]
Hi,
I don't know if that's a common issue or not but I had a few users reporting a total loss of their data on IOs after updating the OS or updating apps.
It might be something in my code but maybe you get similar problems in the past and is a known issue.
I'm not sure if this library is still alive...

**Comment by randycoulman** [comment]
We haven't heard of (or experienced) any data loss issues.

This library is still very much alive, but is not responsible for doing the actual storage.  The storage is actually done by [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info), so you may want to report this issue there.

**Comment by obsidianart** [comment]
Thank you, asking there. Maybe there's a memory limit, I'm surprised I only had the issue on IOs (on Android I have over 10k users and no one ever had the issue).
