### ISSUE TITLE
Why not use the secure branch?

### ISSUE THREAD

**Issue by ItsNoHax** [CodingZeal/redux-persist-sensitive-storage#19]
You mention in the README that there is a branch which is more secure for Android.
What is the reasoning for it not being the standard?

Thanks in advance,
Alberto

**Comment by randycoulman** [comment]
The README is talking about a branch of [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info), not this project.  I'm not sure why it's not the default on that project.  We list react-native-sensitive-info as a peer dependency, so you can choose to use whichever version/branch of that project that is best for your needs.

**Comment by JeremyBradshaw7** [comment]
How do you install that secure branch of react-native-sensitive-info using yarn?
