### ISSUE TITLE
 _reactNativeSensitiveInfo.default.setItem is not a function

### ISSUE THREAD

**Issue by benhurott** [CodingZeal/redux-persist-sensitive-storage#21]
## Sample code

```jsx
import { combineReducers } from 'redux'
import { persistReducer } from 'redux-persist'
import AsyncStorage from '@react-native-community/async-storage'
import AuthReducer from '@redux-sections/auth/reducer'
import ProfileReducer from '@redux-sections/profile/reducer'
import createSensitiveStorage from 'redux-persist-sensitive-storage'

const sensitiveStorage = createSensitiveStorage({
  keychainService: 'myAppKeychain',
  sharedPreferencesName: 'myAppPrefs',
})

const mainPersistConfig = {
  key: 'mainPersist',
  storage: AsyncStorage,
  whitelist: ['profile'],
}

const securePersistConfig = {
  key: 'securePersist',
  storage: sensitiveStorage,
}

const rootReducer = combineReducers({
  auth: persistReducer(securePersistConfig, AuthReducer),
  profile: persistReducer(mainPersistConfig, ProfileReducer),
})

export default rootReducer
```

## Error
![image](https://user-images.githubusercontent.com/3187772/64019010-610c1400-cb04-11e9-9d7a-fb42193cb977.png)

## Info
* react-native: 0.60.4
* redux-persist: 5.10.0
* redux-persist-sensitive-storage: ^1.0.0
* react-native-sensitive-info: ^5.5.0

**Comment by randycoulman** [comment]
I'm not sure what's causing this issue.  I double-checked to make sure that react-native-sensitive-info's API hadn't changed, and it hasn't.

A couple of things you could look at or try:

- Make sure that react-native-sensitive-info has been installed correctly with `react-native link react-native-sensitive-info`.  I'm not sure that's still necessary with the latest React Native, but might be.

- Try doing the following in your code:

```js
import sensitiveInfo from 'react-native-sensitive-info`

console.log(sensitiveInfo)
```

and report back what it tells you.

**Comment by benhurott** [comment]
Hi @randycoulman !

Here is the requested info:

![image](https://user-images.githubusercontent.com/3187772/64338375-f8b3ab80-cfb7-11e9-941e-9880d4f4cea2.png)

**Comment by randycoulman** [comment]
Looks like there's a bunch of stuff missing from that import.  Looking at https://github.com/mCodex/react-native-sensitive-info/blob/master/RNSensitiveInfo.js, you can see that it gets a bunch of stuff from the react-native native modules and adds two additional functions to that (the once you've shown in the output above).

I'm not terribly up-to-date on native modules in react-native, but I'm wondering if the `react-native link` step didn't work on your system, or if something changed in react-native to make this not work properly.

Either way, it seems to be an issue with either that library or your installation of it.  If you can't figure out what's going, I'd suggest filing an issue there.

I'm going to close this one, as I don't think there's anything we can do here.

**Comment by benkissi** [comment]
Getting the same issue

**Comment by salahbm** [comment]
1. Delete the app
2.npm  install react-native-sensitive-info
3. cd ios && pod install
4. npx react-native run-ios
for android no extra steps are needed, hope it helps : )
