### ISSUE TITLE
How to verify it is working?

### ISSUE THREAD

**Issue by erksch** [CodingZeal/redux-persist-sensitive-storage#22]
Hey! 

I followed the README and used the secured storage.
But how can I be sure it is working correctly?

Regards

**Comment by randycoulman** [comment]
If you can persist your Redux store and read it back, then it is working.  If you're asking how to tell that the storage is actually secure, I'm not sure.  We delegate to the [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info) library for that part, so I'd read their documentation about that or ask about it there.
