### ISSUE TITLE
Migrate pre-existing storage on first use 

### ISSUE THREAD

**Issue by JeremyBradshaw7** [CodingZeal/redux-persist-sensitive-storage#27]
This library is great and works well, but it seems doesn't handle pre-existing state (persisted with standard redux-persist) on first use after deployment. This is a big issue for us because we don't want to have to force users to enter pre-login account info again. Are there any guidelines to help with migrating pre-existing state?

Because I only want secure storage one one of my keys, I've moved to using nested persists - could that be the reason I'm losing pre-existing state or is this a generic issue?

**Comment by JeremyBradshaw7** [comment]
I've changed my persists back to the same structure as before and it does now seem to use pre-existing storage from redux-persist on first use. It would still be useful to see somewhere in the docs that this is supported however.

**Comment by lucasfeijo** [comment]
@JeremyBradshaw7 did you find a solution for this? I'm trying to move away from this lib because the data rehydrated on the reducer is corrupted, but if I change the storage medium it crashes in the iOS thread trying to load the sensitive data without the proper code. Seems like once you use this lib you're stuck with it.

**Comment by JeremyBradshaw7** [comment]
> @JeremyBradshaw7 did you find a solution for this? I'm trying to move away from this lib because the data rehydrated on the reducer is corrupted, but if I change the storage medium it crashes in the iOS thread trying to load the sensitive data without the proper code. Seems like once you use this lib you're stuck with it.

My second comment confirmed I got round the original issue. You may be right though I've not tried moving back from secure storage to unsecure storage, that might not be feasible, at least within the same redux reducer, you could possibly persist decrypted storage from a secure reducer to one that isn't if you wanted to revert.

**Comment by gzumaglini** [comment]
The automatic migration did not work for me at all ;(
I created a gist with the code i use to migrate manually at:
https://gist.github.com/gzumaglini/575ee77a601be271583730d007ee2360

**Comment by JeremyBradshaw7** [comment]
@gzumaglini might be worth opening another issue with this detail in, let the package authors clarify.
