### ISSUE TITLE
how can i clear all of my data in redux-persist-sensitive-storage 

### ISSUE THREAD

**Issue by derakhshanfar** [CodingZeal/redux-persist-sensitive-storage#4]
hi, i want to reset my App, how can i clear all of my data in redux-persist-sensitive-storage ?

**Comment by randycoulman** [comment]
You can use the `purge` function provided by redux-persist for this.  See https://github.com/rt2zz/redux-persist#persistor-object.

**Comment by derakhshanfar** [comment]
thanks a lot @randycoulman
