### ISSUE TITLE
what is different between AsyncStorage and persist-sensitive-storage?

### ISSUE THREAD

**Issue by derakhshanfar** [CodingZeal/redux-persist-sensitive-storage#5]
react-native-sensitive-info manages all data stored in Android Shared  Preferences like AsyncStorage..  so what is different?

thanks in advance

**Comment by randycoulman** [comment]
react-native-sensitive-info stores data securely on iOS, and if you use the `keystore` branch, it also stores securely to the keystore on Android.

**Comment by derakhshanfar** [comment]
thanks for answer @randycoulman  but why you don't merge _keystore_ branch with _master_ branch? i installed this package with NPMso how can i import specific branch of this module in my App?

**Comment by randycoulman** [comment]
@derakhshanfar react-native-sensitive-info is not our library, so we don't get to decide when that branch is released to master.
