### ISSUE TITLE
Promise based api

### ISSUE THREAD

**Issue by rt2zz** [CodingZeal/redux-persist-sensitive-storage#6]
redux-persist just switched to requiring promise based storage in v5.0.0-beta.13

Unfortunately it is going to be a pain to get everyone updated. Technically the storage can support both (like AsyncStorage and localforage) but since this module is specific to redux-persist may was well just go 100% promises and make the peer dep be redux-persist@5

**Comment by randycoulman** [comment]
I haven't had a chance to test with redux-persist 5 yet.  Is there a bug here when used with redux-persist 5?

If not, then I don't think it's worth breaking backwards-compatibility just yet.  Once redux-persist 5 is released and widely adopted, then it's worth considering, but until then I think it's best to be more flexible here.

**Comment by rt2zz** [comment]
right, I had not realized this module is already promise compatible https://github.com/CodingZeal/redux-persist-sensitive-storage/blob/master/index.js#L47

So should be good to go :)

redux-persist v5 should be out in the next week or two.

**Comment by randycoulman** [comment]
Cool, thanks @rt2zz!  I appreciate you taking the time to make sure the ecosystem around redux-persist is ready for the upcoming changes.  It's an important, but mostly thankless task, so thanks!
