### ISSUE TITLE
Behaviour of storage on app deletion

### ISSUE THREAD

**Issue by raphkr** [CodingZeal/redux-persist-sensitive-storage#7]
Can you please help me understand as to what happens to the data when the app is uninstalled. Does redux-persist-sensitive-storage keep the data or does it just destroy it ??

**Comment by randycoulman** [comment]
I'm not positive about this, but I believe that on iOS, the data outlives the app, but not a complete wipe of the phone.  On Android, I think the data goes away with the app, but if you use the `keystore` branch it may behave differently.

Ultimately, this library is based on [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info) for the actual storage, so you might get a clearer answer from that project.

Sorry I couldn't be more help.

**Comment by raphkr** [comment]
Sorry for the delayed reply. Thanks for the info.
