### ISSUE TITLE
implement redux-persist-sensitive-storage redux-persist react-native-sensitive-info keystore

### ISSUE THREAD

**Issue by GuillotJessica** [CodingZeal/redux-persist-sensitive-storage#9]
Hello,
What is the best pratices to implement the library.
[There](http://randycoulman.com/blog/2017/07/25/secure-storage-in-react-native/)  @Randy Coulman said 

> We only store API tokens in sensitive storage. Everything else goes in normal storage (AsyncStorage in react-native, for example). You can call redux-persist's `persistStore` function multiple times. Unfortunately, I don't have a code example I can share quickly, but if you could create an issue on the repo, that's something we can look at adding to the documentation.

I want to store 2 tokens, here is my redux/index.js
```
import { combineReducers } from 'redux'
import configureStore from './CreateStore'
import rootSaga from '../Sagas/'
import { persistReducer } from 'redux-persist'
import createSensitiveStorage from "redux-persist-sensitive-storage";


const tokenPersistConfig = {
    key: 'token',
    storage: createSensitiveStorage({
        keychainService: "myKeychain",
        sharedPreferencesName: "mySharedPrefs",
        encrypt: true
    })
};

export default () => {
  /* ------------- Assemble The Reducers ------------- */
  const rootReducer = combineReducers({
    nav: require('./NavigationRedux').reducer,
    github: require('./GithubRedux').reducer,
    login: require('./LoginRedux').reducer,
    search: require('./SearchRedux').reducer,
    filter: require ('./FilterRedux').reducer,
    map: require ('./MapRedux').reducer,
    token: persistReducer(tokenPersistConfig, require('./TokenRedux').reducer),
  });

  return configureStore(rootReducer, rootSaga)
}

```
Here's my package.json
```
    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-sensitive-info": "git://github.com/mCodex/react-native-sensitive-info.git#keystore",
    "redux-persist": "^5.4.0",
    "redux-persist-sensitive-storage": "^1.0.0",
```
Regarding [React Native Sensitive Info](React Native Sensitive Info)
Do I use anywhere setItem getItem deleteItem getAllItems ?

How do I know the encrypt worked?
Where the data are stored exactly?

**Comment by casto101** [comment]
Thanks for your questions! We realize that our documentation hasn't been updated for redux-persist v5, which probably makes things a little confusing. An update will be coming soon, but in the mean time, hopefully this will provide a little clarity.

You mentioned that you need to securely persist two tokens, right? The best thing to do here would be to create a single instance of `createSensitiveStorage` and use it for both tokens. Something like this should be close to what you're looking for. 

```
import { combineReducers } from 'redux'
import configureStore from './CreateStore'
import rootSaga from '../Sagas/'
import { persistReducer } from 'redux-persist'
import createSensitiveStorage from "redux-persist-sensitive-storage";

const sensitiveStorage = createSensitiveStorage({
  keychainService: "myKeychain",
  sharedPreferencesName: "mySharedPrefs",
  encrypt: true
});

const token1PersistConfig = {
  key: 'token1',
  storage: sensitiveStorage
};

const token2PersistConfig = {
  key: 'token2',
  storage: sensitiveStorage
};

export default () => {
  /* ------------- Assemble The Reducers ------------- */
  const rootReducer = combineReducers({
    nav: require('./NavigationRedux').reducer,
    github: require('./GithubRedux').reducer,
    login: require('./LoginRedux').reducer,
    search: require('./SearchRedux').reducer,
    filter: require ('./FilterRedux').reducer,
    map: require ('./MapRedux').reducer,
    token1: persistReducer(token1PersistConfig, require('./Token1Redux').reducer),
    token2: persistReducer(token2PersistConfig, require('./Token2Redux').reducer),
  });

  return configureStore(rootReducer, rootSaga)
}
```

Regarding your other questions:

> Do I use anywhere setItem getItem deleteItem getAllItems ?

These don't need to be used in your code -- redux-persist takes care of that for you. 

> How do I know the encrypt worked?

This package uses [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info) to store and encrypt the data.  That library uses platform-native APIs for storing and retrieving your data.  See their README for more information.

> Where the data are stored exactly?

According to the README for [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info), data is stored in the iOS Keychain and (since you're using the `keystore` branch) the Android Keystore.  If you use the released version of that library, the data will be stored in Android's Shared Preferences and won't be as secure.

**Comment by GuillotJessica** [comment]
nice present for christmas, thx

**Comment by GuillotJessica** [comment]
Do I have to have a persist store? It works fine and then when I reload my emulator, the reducers return null

**Comment by GuillotJessica** [comment]
on the unsigned release it doesn't seam to remember anything either

**Comment by randycoulman** [comment]
@GuillotJessica Sorry for the delayed response.  Are you having a problem with this library in particular, or is it a more general redux-persist issue?  I can't tell from your description.  If it's a more general redux-persist question, you'll probably have more luck asking there.

**Comment by GuillotJessica** [comment]
well I'm not sure myself considering your library is the only way I'm using persit , all I know is my redux doesn't persist using your code in a previous issue,
considering I copy your code I presume it should work
thx

**Comment by randycoulman** [comment]
Unfortunately, I don't have a lot of time to dig into this right now and I haven't had a chance to work with redux-persist v5 yet.  Is your code open-source where I could pull it down to debug it?  Or do you have a small working example that demonstrates the problem?

A couple of things you could try:

- The example code posted above doesn't contain a call to `persistStore`.  It's hard to tell from the redux-persist documentation, but I think that call might still be required when using nested reducers.  So you'd need to do something like `return persistStore(configureStore(rootReducer, rootSaga))` at the end instead.

- If that doesn't help, then you could also try switching over to `AsyncStorage` temporarily as a test to see whether it's an issue with redux-persist usage.

When we get some available time, we'll try putting together an example application, but if you've already got one, that would save us a lot of time.

Thanks!

**Comment by randycoulman** [comment]
I'm going to go ahead and close this.  If there's still an issue here, please re-open or file a new issue.  Thanks!
